### ISSUE TITLE
Render components on homepage

### ISSUE THREAD

**Issue by mitrerogelio** [mitrerogelio/brewlogger#193]
Currently none of the brew methods are rendering on the homepage.

Actual Behavior:

The homepage is blank everywhere except the nav and footer.

Expected Behavior:

Display brewers with their images like in production

**Comment by saboyadev** [comment]
![Screenshot 2024-01-12 at 9 56 38 PM](https://github.com/mitrerogelio/brewlogger/assets/16430662/62b2090a-a41c-40f3-a2a1-9f1219402621)

This is what is currently showing on the homepage without being logged in.

**Comment by saboyadev** [comment]
![Screenshot 2024-01-12 at 9 56 24 PM](https://github.com/mitrerogelio/brewlogger/assets/16430662/b6c7a01b-93a9-4507-a84c-e3303b626b42)

This is what it shows once logged in.
I am trying to understand a bit better what it is that you are trying to accomplish.

**Comment by saboyadev** [comment]
![Screenshot 2024-01-12 at 10 05 16 PM](https://github.com/mitrerogelio/brewlogger/assets/16430662/48974f03-4c81-4669-8eb3-075912c0e077)

Problem was resolved once Firebase configuration was properly integrated.
